name: .NET UnitTests

on:
  push:
    branches: '**'

jobs:
  dotnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Run Tests
      run: dotnet test --no-build -c Release --verbosity normal
      
    - name: Publish ConsoleBuildWinx64
      run: dotnet publish DataInterfaceConsoleTest -c Release -runtime win10-x64 -o publish/win10_x64
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      
    - name: Upload ConsoleBuildWinx64
      uses: actions/upload-artifact@v2
      with:
        name: Console_win10_x64_${{github.sha}}
        path: "publish/_win10_x64*"
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
