name: .NET UnitTests

on:
  [push, pull_request]


jobs:
  dotnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Run Tests
      run: dotnet test --no-build -c Release --verbosity normal
                  
    - name: Publish ConsoleBuildWinx64
      run: dotnet publish DataInterfaceConsole --self-contained false -c Release --runtime win10-x64 -o ~/publish/win10_x64
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/publish' }}
      
    - name: Upload ConsoleBuildWinx64Published
      uses: actions/upload-artifact@v2
      with:
        name: Console_win10_x64_${{github.sha}}
        path: "~/publish/win10_x64/*"
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/publish' }}       
                  
    - name: Publish ConsoleBuildWinx64Standalone
      run: dotnet publish DataInterfaceConsole --self-contained true -c Release --runtime win10-x64 -o ~/publish/standalone/win10_x64
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/publish' }}
      
    - name: Upload ConsoleBuildWinx64PublishedStandalone
      uses: actions/upload-artifact@v2
      with:
        name: Console_win10_x64_standalone_${{github.sha}}
        path: "~/publish/standalone/win10_x64/*"
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/publish' }}
