name: .NET UnitTests

on:
  push:
    branches: '**'

jobs:
  dotnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload ConsoleBuild
      uses: actions/upload-artifact@v2
      with:
        name: console-${{github.sha}}
        path: "DataInterfaceConsoleTest/bin/Release/netcoreapp3.1/*"
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
